Search `schema.d.ts` with environment variable `WEBHOOK_SCHEMA_DTS`
sksat/github-webhook-rs pull request #187
Opened 2024-01-13 14:31 UTC by H1rono

Builds of this crate fails in environments that do not allow unexpected Internet access during the build, such as Nix. This is because `dts_downloader` performs internet access. This PR addresses this issue by providing a way to load local `schema.d.ts`.

Below is a description of how this is done.

1. Determine the path of `schema.d.ts` to be loaded from the environment variable `WEBHOOK_SCHEMA_DTS`.
    - If no environment variable is found, `$OUT_DIR/schema.d.ts` is chosen as the default value.
2. If there is no such file or directory in the specified path, download `schema.d.ts` from the Internet.
    - Downloading is the same as the previous behavior.
3. Generate types from `schema.d.ts`. This generating process is also the same as the previous behavior.

2024-01-13 18:44 UTC, sksat requested changes

2024-01-13 18:44 UTC, sksat commented on github-webhook/build.rs
> +    let out_path_ts = env::var("WEBHOOK_SCHEMA_DTS")
```suggestion
    let out_path_ts = env::var("GITHUB_WEBHOOK_SCHEMA_DTS")
```

2024-01-13 18:48 UTC, sksat commented
Hmmm...
I understand that there are use cases that want to build without internet access (in fact, that's why I deploy my documentation in GitHub Pages instead of docs.rs).

However, I think this change is a bit distorted. Perhaps the reason is that dts-downloader does a lot of things under the name "downloader". This is a problem of the current design, and the fix involves a breaking change. Is it OK to merge this addition after the fix?

2024-01-13 18:59 UTC, H1rono commented
OK! If you open the corresponding issue and assign me, I will gladly create a PR!

2024-01-13 21:48 UTC, sksat commented
FYI: @H1rono `dts-downloader` refactored in #194.
You can add skip download `schema.d.ts` switch in `github-webhook` crate's `build.rs`.

2024-06-24 07:57 UTC, sksat approved these changes
Sorry for super-late review. LGTM.

2024-06-24 07:57 UTC, merged

2024-06-24 08:07 UTC, H1rono commented
thank you! 😄